Provide out of tree variant of tests without building rpms

diff --git a/jenkins-job-builder/job-templates/out-of-tree.yml b/jenkins-job-builder/job-templates/out-of-tree.yml
--- a/jenkins-job-builder/job-templates/out-of-tree.yml
+++ b/jenkins-job-builder/job-templates/out-of-tree.yml
@@ -99,3 +99,97 @@
         - mail-on-fail:
             report-mail-address: '{report-mail-address}'
         - workspace-cleanup
+
+- job-template:
+    name: '{prefix}-outoftree-tests-nobuild-{project}'
+    node: freeipa-runner-{os}
+    defaults: global
+    description: |
+        Run the FreeIPA test suite (sans WebUI & Integration), out-of-tree.
+    wrappers:
+        - workspace-cleanup
+    builders:
+        - clean-up-environment
+        - uninstall-freeipa-packages-soft
+        - clean-user-configuration
+        - configure-updates-testing:
+            enable-updates-testing: "{enable-updates-testing}"
+        - setup-copr-repos:
+            copr-repos: "{copr-repos}"
+        - shell: |
+            sudo dnf distro-sync --allowerasing -y
+        - install-freeipa-packages
+        # repositories cleanup
+        - disable-updates-testing
+        - remove-copr-repos:
+            copr-repos: "{copr-repos}"
+        - install:
+            options-dns-setup: "{options-dns-setup}"
+            options-ca-setup: "{options-ca-setup}"
+        - kra-install
+        - setup-default-conf
+        - copy-pw-files
+        - shell: |
+            # Jenkins sets the PATH to its own default,
+            # compensate so ipa-getkeytab can be found
+            export PATH=$PATH:/usr/sbin
+
+            ipa-run-tests -v --with-xunit --ignore test_integration --ignore test_webui \
+                --ignore test_xmlrpc/test_trust_plugin.py \
+                --ignore test_xmlrpc/test_external_members.py || :
+        - kra-uninstall
+        - uninstall
+        - clean-user-configuration
+        - clean-httpd-dir
+        - uninstall-freeipa-packages
+    publishers:
+        - nosetests-xunit
+        - mail-on-fail:
+            report-mail-address: '{report-mail-address}'
+        - workspace-cleanup
+
+- job-template:
+    name: '{prefix}-outoftree-tests-with-trust-nobuild-{project}'
+    node: freeipa-runner-{os}
+    defaults: global
+    description: |
+        Run the FreeIPA test suite (sans WebUI & Integration), out-of-tree.
+    wrappers:
+        - workspace-cleanup
+    builders:
+        - clean-up-environment
+        - uninstall-freeipa-packages-soft
+        - clean-user-configuration
+        - configure-updates-testing:
+            enable-updates-testing: "{enable-updates-testing}"
+        - setup-copr-repos:
+            copr-repos: "{copr-repos}"
+        - shell: |
+            sudo dnf distro-sync --allowerasing -y
+        - install-freeipa-packages
+        # repositories cleanup
+        - disable-updates-testing
+        - remove-copr-repos:
+            copr-repos: "{copr-repos}"
+        - install:
+            options-dns-setup: "{options-dns-setup}"
+            options-ca-setup: "{options-ca-setup}"
+        - trust-setup
+        - setup-default-conf
+        - copy-pw-files
+        - shell: |
+            # Jenkins sets the PATH to its own default,
+            # compensate so ipa-getkeytab can be found
+            export PATH=$PATH:/usr/sbin
+
+            ipa-run-tests -v --with-xunit test_xmlrpc/test_trust_plugin.py \
+                test_xmlrpc/test_external_members.py || :
+        - uninstall
+        - clean-user-configuration
+        - clean-httpd-dir
+        - uninstall-freeipa-packages
+    publishers:
+        - nosetests-xunit
+        - mail-on-fail:
+            report-mail-address: '{report-mail-address}'
+        - workspace-cleanup
